name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: ${{ secrets.DEBUG }}
      MAX_PDF_SIZE_MB: 50
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
              
    - name: Install Pipenv
      run: pip install pipenv

    - name: Install dependencies
      run:  python -V & python -m pipenv install -d 

    - name: Tests
      run:  python -m pipenv run test

    - name: Lint
      run:  python -m pipenv run lint

    - name: Scan
      run:  python -m pipenv run scan
